
import { useState } from "react";
import Card from "./Card";

//TODO: Change to using UUID
//TODO: Check if I should use keys?
//TODO: API images

function Gameboard({score, setScore, hiScore, setHiScore}){

    const [cardsClicked, setCardsClicked] = useState([]); // Tracks the cards selected. Each card has a key generated by UUID (?)
    const [cardsOrder, setCardsOrder] = useState([1,2,3,4,5,6,7,8]); // Tracks the cards selected. Each card has a key generated by UUID (?)


    // Returns a new array that is a result of shuffling the given arr
    function shuffle(arr) {
        let array = arr;
        let currentIndex = array.length,  randomIndex;
        
        // While there remain elements to shuffle.
        while (currentIndex > 0) {

            // Pick a remaining element.
            randomIndex = Math.floor(Math.random() * currentIndex);
            currentIndex--;

            // And swap it with the current element.
            [array[currentIndex], array[randomIndex]] = [
            array[randomIndex], array[currentIndex]];
        }

        return array;
    }

    function handleClick(e){
       
        if (cardsClicked.includes(e.target.id)){
            alert("YOU LOSE")         
            if (score > hiScore) setHiScore(score);
            setScore(0);
            setCardsClicked([]);
        } else {

            if (score == cardsOrder.length-1){ //Score wont be accurate until page is re-rendered
                alert("YOU WIN");
                setScore(0);
                setHiScore(0);
                setCardsClicked([]);
                setCardsOrder([1,2,3,4,5,6,7,8]);
                return;
            }
            setScore(score+1); 
            setCardsClicked(cardsClicked.concat(e.target.id))
            setCardsOrder(shuffle(cardsOrder))
            
        }
    }

    return(
        <div className="board">
            {
                cardsOrder.map((cardID) => {
                    return <div className="card" id={cardID} onClick={handleClick}>{cardID}</div>
                })
            }
        </div>
    )
}

export default Gameboard;