
import { useState } from "react";
import Card from "./Card";

//TODO: Change to using UUID
//TODO: Check if I should use keys?
//TODO: API images

function Gameboard({score, setScore, hiScore, setHiScore}){

    const [cardsClicked, setCardsClicked] = useState([]); // Tracks the cards selected. Each card has a key generated by UUID (?)

    // Re-arranges cards on the board
    function randomizeBoard(){
        // alert("BOARD RANDOMIZED")
    }
    // const handleSubmit = (e) => {

    function handleClick(e){
        // Check if we previously clicked card. IF we did, game over
        if (cardsClicked.includes(e.target.id)){        
            alert("GAME OVER");
            if (score > hiScore) setHiScore(score);
            setScore(0);
            setCardsClicked([]);
        } else {
            setCardsClicked(cardsClicked.concat(e.target.id))
            randomizeBoard();
            setScore(score+1);
        }
    }

    return(
        <div className="board">
            <div className="card" id="1" onClick={handleClick}>1</div>
            <div className="card" id="2" onClick={handleClick}>2</div>
            <div className="card" id="3" onClick={handleClick}>3</div>
            <div className="card" id="4" onClick={handleClick}>4</div>
        </div>
    )
}

export default Gameboard;